'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditGallery

 '''<summary>
 '''dlExisting control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlExisting As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''pnlUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlUpload As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''plFile control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plFile As Global.System.Web.UI.UserControl

 '''<summary>
 '''ctlUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ctlUpload As Global.System.Web.UI.WebControls.FileUpload

 '''<summary>
 '''plTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTitle As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plRemarks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plRemarks As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRemarks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''cmdUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpload As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''cmdReturn control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton
End Class
