'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

 '''<summary>
 '''plWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator1 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plHeight As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtHeight As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator2 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator2 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator2 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plFitType control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plFitType As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddFitType control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddFitType As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plZoomWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtZoomWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtZoomWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator3 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator3 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator3 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plZoomHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomHeight As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtZoomHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtZoomHeight As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator4 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator4 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator4 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plZoomFitType control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomFitType As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddZoomFitType control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddZoomFitType As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plRegenerate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plRegenerate As Global.System.Web.UI.UserControl

 '''<summary>
 '''cmdRegenerate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdRegenerate As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''plTemplate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTemplate As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddTemplate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddTemplate As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plhTemplateDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plhTemplateDescription As Global.System.Web.UI.WebControls.PlaceHolder
End Class
