$(document).ready(function () {
 $('#fb[settings:moduleid] a').fancybox({
padding: [settings:padding],
margin: [settings:margin],
opacity: [settings:opacity],
modal: [settings:modal],
cyclic: [settings:cyclic],
scrolling: '[settings:scrolling]',
width: [settings:width],
height: [settings:height],
autoScale: [settings:autoScale],
autoDimensions: [settings:autoDimensions],
centerOnScroll: [settings:centerOnScroll],
swf: [settings:swf],
hideOnOverlayClick: [settings:hideOnOverlayClick],
hideOnContentClick: [settings:hideOnContentClick],
overlayShow: [settings:overlayShow],
overlayOpacity: [settings:overlayOpacity],
overlayColor: '[settings:overlayColor]',
titleShow: [settings:titleShow],
titlePosition: '[settings:titlePosition]',
titleFormat: [settings:titleFormat],
transitionIn: '[settings:transitionIn]',
transitionOut: '[settings:transitionOut]',
speedIn: [settings:speedIn],
speedOut: [settings:speedOut],
changeSpeed: [settings:changeSpeed],
changeFade: '[settings:changeFade]',
easingIn: '[settings:easingIn]',
easingOut: '[settings:easingOut]',
showCloseButton: [settings:showCloseButton],
showNavArrows: [settings:showNavArrows],
enableEscapeButton: [settings:enableEscapeButton]
 });
});
