$(document).ready(function () {
 $('#colorbox[settings:moduleid] a').colorbox({
transition: "[settings:transition]",
speed: [settings:speed],
rel: [settings:rel],
width: [settings:width],
height: [settings:height],
innerWidth: [settings:innerWidth],
innerHeight: [settings:innerHeight],
initialWidth: [settings:initialWidth],
initialHeight: [settings:initialHeight],
maxWidth: [settings:maxWidth],
maxHeight: [settings:maxHeight],
scalePhotos: [settings:scalePhotos],
scrolling: [settings:scrolling],
photo: [settings:photo],
opacity: [settings:opacity],
open: [settings:open],
returnFocus: [settings:returnFocus],
preloading: [settings:preloading],
overlayClose: [settings:overlayClose],
escKey: [settings:escKey],
arrowKey: [settings:arrowKey],
loop: [settings:loop],
slideshow: [settings:slideshow],
slideshowSpeed: [settings:slideshowSpeed],
slideshowAuto: [settings:slideshowAuto],
slideshowStart: "[resx:slideshowStart]",
slideshowStop: "[resx:slideshowStop]",
current: "[resx:current]",
previous: "[resx:previous]",
next: "[resx:next]",
close: "[resx:close]"
 });
});
