$(document).ready(function () {
 $('#p[settings:moduleid]').cycle({ fx: '[settings:fx]',
 autostop: [settings:autostop],
 autostopCount: [settings:autostopCount],
 backwards: [settings:backwards],
 cleartypeNoBg: [settings:cleartypeNoBg],
 containerResize: [settings:containerResize],
 continuous: [settings:continuous],
 delay: [settings:delay],
 fastOnEvent: [settings:fastOnEvent],
 fit: [settings:fit],
 height: '[settings:height]',
 manualTrump: [settings:manualTrump],
 nowrap: [settings:nowrap],
 pause: [settings:pause],
 random: [settings:random],
 randomizeEffects: [settings:randomizeEffects],
 requeueOnImageNotLoaded: [settings:requeueOnImageNotLoaded],
 requeueTimeout: [settings:requeueTimeout],
 rev: [settings:rev],
 slideResize: [settings:slideResize],
 speed: [settings:speed],
 sync: [settings:sync],
 timeout: [settings:timeout]
 });
});
