'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SharedResources_ascx
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bring2mind.DNN.Modules.YAG.SharedResources.ascx", GetType(SharedResources_ascx).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resize the photos bigger than viewport. true/false.
        '''</summary>
        Friend Shared ReadOnly Property allow_resize_Help() As String
            Get
                Return ResourceManager.GetString("allow_resize.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Resize.
        '''</summary>
        Friend Shared ReadOnly Property allow_resize_Text() As String
            Get
                Return ResourceManager.GetString("allow_resize.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fast/slow/normal.
        '''</summary>
        Friend Shared ReadOnly Property animation_speed_Help() As String
            Get
                Return ResourceManager.GetString("animation_speed.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Animation Speed.
        '''</summary>
        Friend Shared ReadOnly Property animation_speed_Text() As String
            Get
                Return ResourceManager.GetString("animation_speed.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatically start videos: True/False.
        '''</summary>
        Friend Shared ReadOnly Property autoplay_Help() As String
            Get
                Return ResourceManager.GetString("autoplay.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Whether to start playing slideshow when a user clicks on an image.
        '''</summary>
        Friend Shared ReadOnly Property autoplay_slideshow_Help() As String
            Get
                Return ResourceManager.GetString("autoplay_slideshow.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autoplay Slideshow.
        '''</summary>
        Friend Shared ReadOnly Property autoplay_slideshow_Text() As String
            Get
                Return ResourceManager.GetString("autoplay_slideshow.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autoplay.
        '''</summary>
        Friend Shared ReadOnly Property autoplay_Text() As String
            Get
                Return ResourceManager.GetString("autoplay.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The padding on each side of the picture.
        '''</summary>
        Friend Shared ReadOnly Property horizontal_padding_Help() As String
            Get
                Return ResourceManager.GetString("horizontal_padding.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Horizontal Padding.
        '''</summary>
        Friend Shared ReadOnly Property horizontal_padding_Text() As String
            Get
                Return ResourceManager.GetString("horizontal_padding.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow use of keyboard to navigate..
        '''</summary>
        Friend Shared ReadOnly Property keyboard_shortcuts_Help() As String
            Get
                Return ResourceManager.GetString("keyboard_shortcuts.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keyboard Shortcuts.
        '''</summary>
        Friend Shared ReadOnly Property keyboard_shortcuts_Text() As String
            Get
                Return ResourceManager.GetString("keyboard_shortcuts.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, only the close button will close the window.
        '''</summary>
        Friend Shared ReadOnly Property modal_Help() As String
            Get
                Return ResourceManager.GetString("modal.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modal Window.
        '''</summary>
        Friend Shared ReadOnly Property modal_Text() As String
            Get
                Return ResourceManager.GetString("modal.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to opacity of the overlay.
        '''</summary>
        Friend Shared ReadOnly Property opacity_Help() As String
            Get
                Return ResourceManager.GetString("opacity.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opacity.
        '''</summary>
        Friend Shared ReadOnly Property opacity_Text() As String
            Get
                Return ResourceManager.GetString("opacity.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If checked, a gallery will overlay the fullscreen image on mouse over.
        '''</summary>
        Friend Shared ReadOnly Property overlay_gallery_Help() As String
            Get
                Return ResourceManager.GetString("overlay_gallery.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overlay Gallery.
        '''</summary>
        Friend Shared ReadOnly Property overlay_gallery_Text() As String
            Get
                Return ResourceManager.GetString("overlay_gallery.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Whether to show the title above the image.
        '''</summary>
        Friend Shared ReadOnly Property show_title_Help() As String
            Get
                Return ResourceManager.GetString("show_title.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Title.
        '''</summary>
        Friend Shared ReadOnly Property show_title_Text() As String
            Get
                Return ResourceManager.GetString("show_title.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to false OR interval time in ms.
        '''</summary>
        Friend Shared ReadOnly Property slideshow_Help() As String
            Get
                Return ResourceManager.GetString("slideshow.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slideshow speed.
        '''</summary>
        Friend Shared ReadOnly Property slideshow_Text() As String
            Get
                Return ResourceManager.GetString("slideshow.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose from.
        '''</summary>
        Friend Shared ReadOnly Property theme_Help() As String
            Get
                Return ResourceManager.GetString("theme.Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Theme.
        '''</summary>
        Friend Shared ReadOnly Property theme_Text() As String
            Get
                Return ResourceManager.GetString("theme.Text", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
